# Generated by Django 6.0.3 on 2026-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unlimited_ai',
            field=models.BooleanField(default=False),
        ),
    ]
