#!/bin/bash
# Conventional Commit Message Check
#
# Enforces conventional commit format:
#   type(scope): description
#   type: description
#   type!: description (breaking change)
#   type(scope)!: description (breaking change)
#
# Valid types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
#
# Exit 0: Valid commit message
# Exit 1: Invalid format

set -e

# Hook logging setup
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_LOG_DIR="$SCRIPT_DIR/../logs"
HOOK_LOG="$HOOK_LOG_DIR/hooks.log"
mkdir -p "$HOOK_LOG_DIR"

log_hook() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [commit-msg] $1" >> "$HOOK_LOG"
}

# Get commit message file (passed by git)
COMMIT_MSG_FILE="$1"

if [[ -z "$COMMIT_MSG_FILE" ]] || [[ ! -f "$COMMIT_MSG_FILE" ]]; then
    log_hook "ERROR: No commit message file provided"
    echo "[commit-msg] No commit message file provided"
    exit 1
fi

# Read commit message (first non-comment line)
COMMIT_MSG=$(grep -v '^#' "$COMMIT_MSG_FILE" | head -1)

# Skip if empty (e.g., merge commits handled by git)
if [[ -z "$COMMIT_MSG" ]]; then
    log_hook "SKIP: Empty commit message"
    exit 0
fi

# Skip merge commits
if echo "$COMMIT_MSG" | grep -qE '^Merge (branch|pull request|remote-tracking|tag)'; then
    log_hook "SKIP: Merge commit"
    exit 0
fi

# Skip revert commits (auto-generated by git)
if echo "$COMMIT_MSG" | grep -qE '^Revert "'; then
    log_hook "SKIP: Revert commit"
    exit 0
fi

# Skip fixup and squash commits (used with git rebase --autosquash)
if echo "$COMMIT_MSG" | grep -qE '^(fixup|squash|amend)! '; then
    log_hook "SKIP: Fixup/squash commit"
    exit 0
fi

# Skip WIP commits (work in progress)
if echo "$COMMIT_MSG" | grep -qiE '^WIP[: ]'; then
    log_hook "SKIP: WIP commit"
    exit 0
fi

# Valid conventional commit types
TYPES="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"

# Pattern: type(scope)!: description OR type!: description OR type(scope): description OR type: description
# - Type is required
# - Scope is optional (in parentheses, allows lowercase, numbers, hyphens, underscores)
# - Breaking change indicator ! is optional
# - Colon and space after type/scope
# - Description is required
PATTERN="^($TYPES)(\([a-z0-9_-]+\))?!?: .+"

if ! echo "$COMMIT_MSG" | grep -qE "$PATTERN"; then
    log_hook "BLOCKED: Invalid commit message format"
    echo ""
    echo "INVALID COMMIT MESSAGE FORMAT"
    echo "=============================="
    echo ""
    echo "Your message:"
    echo "  $COMMIT_MSG"
    echo ""
    echo "Expected format:"
    echo "  type(scope): description"
    echo "  type: description"
    echo "  type!: breaking change description"
    echo "  type(scope)!: breaking change description"
    echo ""
    echo "Valid types:"
    echo "  feat     - New feature"
    echo "  fix      - Bug fix"
    echo "  docs     - Documentation only"
    echo "  style    - Formatting, no code change"
    echo "  refactor - Code change that neither fixes nor adds"
    echo "  perf     - Performance improvement"
    echo "  test     - Adding/updating tests"
    echo "  build    - Build system or dependencies"
    echo "  ci       - CI configuration"
    echo "  chore    - Other changes (e.g., .gitignore)"
    echo "  revert   - Revert a previous commit"
    echo ""
    echo "Examples:"
    echo "  feat(auth): add login page"
    echo "  fix: resolve null pointer in search"
    echo "  feat!: redesign API endpoints"
    echo "  docs(api): update endpoint documentation"
    echo ""
    echo "To skip (not recommended): git commit --no-verify"
    echo ""
    exit 1
fi

log_hook "PASS: Valid commit message"
exit 0
