# Generated by Django 6.0.3 on 2026-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='default_ai_model',
            field=models.CharField(default='anthropic/claude-haiku-4.5', max_length=100),
        ),
    ]
