# Generated by Django 6.0.2 on 2026-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='openrouter_api_key',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='_openrouter_api_key',
            field=models.CharField(blank=True, db_column='openrouter_api_key', max_length=500),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='deployment_mode',
            field=models.CharField(choices=[('home', 'Home Server'), ('public', 'Public Hosting')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='instance_name',
            field=models.CharField(default='Cookie', max_length=100),
        ),
    ]
