# Generated by Django 6.0.3 on 2026-03-28 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passkey_webauthn_devicecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecode',
            name='authorizing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_device_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicecode',
            name='code',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
