# Generated by Django 6.0.3 on 2026-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passkey_model_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='credential_id',
            field=models.BinaryField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='public_key',
            field=models.BinaryField(max_length=1024),
        ),
    ]
