# Generated by Django 6.0.3 on 2026-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passkey_field_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='daily_limit_discover',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_limit_remix',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_limit_remix_suggestions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_limit_scale',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_limit_timer',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='daily_limit_tips',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
