# Generated by Django 5.2.10 on 2026-01-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_update_serving_adjustment_v2'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='prompt_type',
            field=models.CharField(choices=[('recipe_remix', 'Recipe Remix'), ('serving_adjustment', 'Serving Adjustment'), ('tips_generation', 'Tips Generation'), ('nutrition_estimate', 'Nutrition Estimate'), ('discover_favorites', 'Discover from Favorites'), ('discover_seasonal', 'Discover Seasonal/Holiday'), ('discover_new', 'Discover Try Something New'), ('search_ranking', 'Search Result Ranking'), ('timer_naming', 'Timer Naming'), ('remix_suggestions', 'Remix Suggestions'), ('selector_repair', 'CSS Selector Repair')], help_text='Unique identifier for this prompt type', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='AIDiscoverySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('favorites', 'Based on Favorites'), ('seasonal', 'Seasonal/Holiday'), ('new', 'Try Something New')], help_text='Type of discovery suggestion', max_length=50)),
                ('search_query', models.CharField(help_text='Search query to execute for this suggestion', max_length=255)),
                ('title', models.CharField(help_text='Display title for this suggestion', max_length=255)),
                ('description', models.TextField(help_text='Explanation of why this suggestion fits the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(help_text='Profile this suggestion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ai_discovery_suggestions', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'AI Discovery Suggestion',
                'verbose_name_plural': 'AI Discovery Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'suggestion_type', 'created_at'], name='ai_aidiscov_profile_8129f7_idx')],
            },
        ),
    ]
