# Generated by Django 6.0.3 on 2026-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_fix_discover_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='model',
            field=models.CharField(choices=[('anthropic/claude-haiku-4.5', 'Claude Haiku 4.5 (Fast)'), ('anthropic/claude-sonnet-4', 'Claude Sonnet 4'), ('anthropic/claude-opus-4', 'Claude Opus 4'), ('anthropic/claude-opus-4.5', 'Claude Opus 4.5'), ('openai/gpt-4o', 'GPT-4o'), ('openai/gpt-4o-mini', 'GPT-4o Mini (Fast)'), ('openai/gpt-5-mini', 'GPT-5 Mini'), ('openai/o3-mini', 'o3 Mini (Reasoning)'), ('google/gemini-2.5-pro-preview', 'Gemini 2.5 Pro'), ('google/gemini-2.5-flash-preview', 'Gemini 2.5 Flash (Fast)')], default='anthropic/claude-haiku-4.5', help_text='AI model to use for this prompt', max_length=100),
        ),
    ]
