# Generated by Django 5.2.10 on 2026-01-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('search_url_template', models.CharField(max_length=500)),
                ('result_selector', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('needs_attention', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, db_index=True, max_length=2000, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000)),
                ('host', models.CharField(max_length=255)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='recipe_images/')),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('ingredients', models.JSONField(default=list)),
                ('ingredient_groups', models.JSONField(default=list)),
                ('instructions', models.JSONField(default=list)),
                ('instructions_text', models.TextField(blank=True)),
                ('prep_time', models.PositiveIntegerField(blank=True, null=True)),
                ('cook_time', models.PositiveIntegerField(blank=True, null=True)),
                ('total_time', models.PositiveIntegerField(blank=True, null=True)),
                ('yields', models.CharField(blank=True, max_length=100)),
                ('servings', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('cooking_method', models.CharField(blank=True, max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('dietary_restrictions', models.JSONField(default=list)),
                ('equipment', models.JSONField(default=list)),
                ('nutrition', models.JSONField(default=dict)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('links', models.JSONField(default=list)),
                ('ai_tips', models.JSONField(blank=True, default=list)),
                ('is_remix', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remix_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remixes', to='profiles.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['host'], name='recipes_rec_host_5552ca_idx'), models.Index(fields=['is_remix'], name='recipes_rec_is_remi_f9e83c_idx'), models.Index(fields=['scraped_at'], name='recipes_rec_scraped_1431f9_idx')],
            },
        ),
    ]
