# Generated by Django 5.2.10 on 2026-01-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipecollection_recipecollectionitem_recipefavorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedSearchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(db_index=True, max_length=2000, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='search_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='recipes_cac_status_b3d328_idx'), models.Index(fields=['created_at'], name='recipes_cac_created_15879c_idx')],
            },
        ),
    ]
