# Generated by Django 5.2.10 on 2026-01-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('recipes', '0004_cachedsearchimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_servings', models.PositiveIntegerField()),
                ('unit_system', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10)),
                ('ingredients', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_adjustments', to='profiles.profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_adjustments', to='recipes.recipe')),
            ],
            options={
                'indexes': [models.Index(fields=['recipe', 'profile'], name='recipes_ser_recipe__b2036d_idx')],
                'unique_together': {('recipe', 'profile', 'target_servings', 'unit_system')},
            },
        ),
    ]
