# Generated by Django 5.2.10 on 2026-01-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recipe',
            new_name='recipes_rec_profile_7945b8_idx',
            old_name='recipes_rec_profile_idx',
        ),
    ]
