# Generated by Django 6.0.2 on 2026-02-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('recipes', '0009_add_default_selectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='remixed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remix_children', to='recipes.recipe'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['remixed_from'], name='recipes_rec_remixed_10f7b1_idx'),
        ),
    ]
